sculpin:
    ignore: ["*.swp"]
sculpin_theme:
    theme: sculpin/bootstrap-3-blog-theme
sculpin_content_types:
    posts:
        permalink: docs/changelog/:year/:month/
        path: _changelog
        enabled: true
    docs:
        type: path
        path: _docs
        singular_name: doc
        enabled: true
        taxonomies:
            - categories
            - tags
            - contributors
        permalink: docs/:basename/
    guides:
        type: meta
        taxonomies:
            - categories
            - tags
            - contributors
    videos:
        type: meta
        taxonomies:
            - categories
            - tags
            - contributors

    quickstartpages:
        type: path
        path: docs/guides/quickstart
        permalink: pretty
        singular_name: quickstartpage
        enabled: true
        layout: guide
        taxonomies:
            - categories
            - tags
            - contributors
